from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Iterable

from .io_utils import read_review_tsv, read_segments
from .models import Segment

STYLE_COLORS = [
    "&H0000A8FA",
    "&H00F9C304",
    "&H00F26BBE",
    "&H0076E07A",
    "&H00FFFFFF",
]


def _parse_ass_color(value: str) -> tuple[int, int, int, int]:
    color = value.removeprefix("&H").removesuffix("&").rjust(8, "0")
    alpha = int(color[0:2], 16)
    blue = int(color[2:4], 16)
    green = int(color[4:6], 16)
    red = int(color[6:8], 16)
    return red, green, blue, alpha


def ass_time(seconds: float) -> str:
    seconds = max(0.0, seconds)
    centiseconds = int(round(seconds * 100))
    cs = centiseconds % 100
    total_seconds = centiseconds // 100
    sec = total_seconds % 60
    total_minutes = total_seconds // 60
    minute = total_minutes % 60
    hour = total_minutes // 60
    return f"{hour}:{minute:02d}:{sec:02d}.{cs:02d}"


def escape_ass_text(text: str) -> str:
    return text.replace("\r\n", "\n").replace("\r", "\n").replace("\n", r"\N")


def _style_name(index: int) -> str:
    return f"speaker{index}"


def _speaker_order(segments: Iterable[Segment]) -> list[str]:
    seen: dict[str, None] = {}
    for segment in segments:
        seen.setdefault(segment.speaker, None)
    return list(seen)


def load_speaker_map(path: str | Path | None) -> dict[str, str]:
    if path is None:
        return {}
    with Path(path).open("r", encoding="utf-8") as handle:
        raw = json.load(handle)
    result: dict[str, str] = {}
    for key, value in raw.items():
        if isinstance(value, str):
            result[str(key)] = value
        elif isinstance(value, dict):
            result[str(key)] = str(value.get("name") or key)
    return result


def _assign_lanes(segments: list[Segment]) -> dict[int, int]:
    """Assign vertical lanes so overlapping segments render side by side."""

    lanes: dict[int, int] = {}
    active: list[tuple[float, int]] = []
    for index, segment in enumerate(segments):
        active = [(end, lane) for end, lane in active if end > segment.start]
        occupied = {lane for _, lane in active}
        lane = 0
        while lane in occupied:
            lane += 1
        lanes[index] = lane
        active.append((segment.end, lane))
    return lanes


def _manual_ass(segments: list[Segment], speaker_map: dict[str, str]) -> str:
    speakers = _speaker_order(segments)
    style_by_speaker = {speaker: _style_name(index) for index, speaker in enumerate(speakers)}
    lanes = _assign_lanes(segments)

    lines = [
        "[Script Info]",
        "; Script generated by drama-nemo-ass",
        "ScriptType: v4.00+",
        "PlayResX: 1920",
        "PlayResY: 1080",
        "Timer: 100.0000",
        "YCbCr Matrix: TV.709",
        "",
        "[V4+ Styles]",
        (
            "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, "
            "Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, "
            "Shadow, Alignment, MarginL, MarginR, MarginV, Encoding"
        ),
        (
            "Style: Default,Arial,36,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,"
            "0,0,0,0,100,100,0,0,1,3,3,2,15,15,15,1"
        ),
    ]
    for index, speaker in enumerate(speakers):
        color = STYLE_COLORS[index % len(STYLE_COLORS)]
        lines.append(
            f"Style: {style_by_speaker[speaker]},Arial,48,{color},&H000000FF,&H00000000,&H00000000,"
            "0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1"
        )

    lines.extend(
        [
            "",
            "[Events]",
            "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
        ]
    )
    for index, segment in enumerate(segments):
        style = style_by_speaker.get(segment.speaker, "Default")
        name = speaker_map.get(segment.speaker, segment.speaker)
        lane = lanes.get(index, 0)
        margin_v = 15 + lane * 55
        lines.append(
            "Dialogue: 0,{start},{end},{style},{name},0,0,{margin},,{text}".format(
                start=ass_time(segment.start),
                end=ass_time(segment.end),
                style=style,
                name=name,
                margin=margin_v,
                text=escape_ass_text(segment.text),
            )
        )
    return "\n".join(lines) + "\n"


def _try_pysubs2(segments: list[Segment], speaker_map: dict[str, str], output_path: Path) -> bool:
    try:
        import pysubs2
    except ImportError:
        return False

    try:
        subs = pysubs2.SSAFile()
        subs.info["ScriptType"] = "v4.00+"
        subs.info["PlayResX"] = "1920"
        subs.info["PlayResY"] = "1080"
        speakers = _speaker_order(segments)
        style_by_speaker = {speaker: _style_name(index) for index, speaker in enumerate(speakers)}
        for index, speaker in enumerate(speakers):
            style = pysubs2.SSAStyle()
            style.fontname = "Arial"
            style.fontsize = 48
            red, green, blue, alpha = _parse_ass_color(STYLE_COLORS[index % len(STYLE_COLORS)])
            style.primarycolor = pysubs2.Color(red, green, blue, alpha)
            style.outline = 2
            style.shadow = 2
            style.alignment = 2
            subs.styles[style_by_speaker[speaker]] = style
        lanes = _assign_lanes(segments)
        for index, segment in enumerate(segments):
            event = pysubs2.SSAEvent(
                start=int(round(segment.start * 1000)),
                end=int(round(segment.end * 1000)),
                style=style_by_speaker.get(segment.speaker, "Default"),
                name=speaker_map.get(segment.speaker, segment.speaker),
                text=escape_ass_text(segment.text),
            )
            event.margin_v = 15 + lanes.get(index, 0) * 55
            subs.events.append(event)
        subs.save(str(output_path))
        return True
    except Exception:
        return False


def render_ass(
    segments: Iterable[Segment],
    output_path: str | Path,
    speaker_map_path: str | Path | None = None,
    prefer_pysubs2: bool = True,
) -> Path:
    target = Path(output_path)
    target.parent.mkdir(parents=True, exist_ok=True)
    ordered_segments = sorted(list(segments), key=lambda item: (item.start, item.end, item.speaker))
    speaker_map = load_speaker_map(speaker_map_path)
    if prefer_pysubs2 and _try_pysubs2(ordered_segments, speaker_map, target):
        return target
    target.write_text(_manual_ass(ordered_segments, speaker_map), encoding="utf-8", newline="\n")
    return target


def render_out_dir(
    out_dir: str | Path,
    speaker_map_path: str | Path | None = None,
    source: str = "auto",
    prefer_pysubs2: bool = True,
) -> Path:
    out = Path(out_dir)
    if source not in {"auto", "review", "segments", "overlap"}:
        raise ValueError("source must be one of auto, review, segments, or overlap")
    review_path = out / "review.tsv"
    overlap_path = out / "segments_overlap.json"
    if source == "overlap" or (source == "auto" and overlap_path.exists()):
        segments = read_segments(overlap_path)
    elif source == "review" or (source == "auto" and review_path.exists()):
        segments = read_review_tsv(review_path)
    else:
        segments = read_segments(out / "segments.json")
    return render_ass(segments, out / "output.ass", speaker_map_path=speaker_map_path, prefer_pysubs2=prefer_pysubs2)


ASS_TAG_RE = re.compile(r"\{[^}]*\}")


def plain_ass_text(text: str) -> str:
    return ASS_TAG_RE.sub("", text).replace(r"\N", "\n").strip()
